In [1]:
import numpy as np
import pandas as pd

### Import sensor data. Note that you can download this using the airmove dashboard

In [2]:
sensor_data = pd.read_csv('sensor_data/sensor_data_1.csv')
sensor_data

,local_time,source,gps_lat,gps_long,bmp280_tmp,hdc1080_rh,hdc1080_tmp,si7020_rh,si7020_tmp,sen0321_o3,...,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm25_emb,pm10_who,pm10_emb,o3_who
0,2023-08-01 01:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,99.978085,26.991489,0.020447,...,64.0,37.0,19.606596,19.0,19.0,15,NaN,45,NaN,0.05
1,2023-08-01 02:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,100.000000,26.985965,0.020000,...,57.0,30.0,17.177778,16.0,16.0,15,NaN,45,NaN,0.05
2,2023-08-01 03:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,100.000000,27.002203,0.020000,...,54.0,27.0,15.962159,15.0,15.0,15,NaN,45,NaN,0.05
3,2023-08-01 04:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,100.000000,27.001167,0.020000,...,52.0,26.0,15.595743,15.0,15.0,15,NaN,45,NaN,0.05
4,2023-08-01 05:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,100.000000,27.016949,0.020000,...,53.0,26.0,15.708931,15.0,15.0,15,NaN,45,NaN,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5795,2024-03-29 12:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,19.578167,26.508167,0.035050,...,30.0,15.0,13.397823,12.0,12.0,15,NaN,45,NaN,0.05
5796,2024-03-29 13:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,17.895085,29.815085,0.049831,...,29.0,14.0,13.017644,12.0,12.0,15,NaN,45,NaN,0.05
5797,2024-03-29 14:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,99.204333,33.690333,0.074100,...,29.0,14.0,12.870821,12.0,12.0,15,NaN,45,NaN,0.05
5798,2024-03-29 15:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,89.525763,36.905932,0.071831,...,27.0,13.0,12.651798,12.0,12.0,15,NaN,45,NaN,0.05
5799,2024-03-29 16:00,9ef4b83d,14.6474,121.072,NaN,NaN,NaN,81.183000,38.096333,0.074750,...,27.0,13.0,12.296155,11.0,11.0,15,NaN,45,NaN,0.05

### Cleanup data
Check for columns containing only NaN values

In [3]:
# Step 2: Check for columns containing only NaN values
nan_columns = []
for column in sensor_data.columns:
    if sensor_data[column].isnull().all():
        nan_columns.append(column)

# Step 3: Remove columns containing only NaN values
sensor_data = sensor_data.drop(nan_columns, axis=1)

# Step 4: Display the resulting DataFrame
sensor_data

,local_time,source,gps_lat,gps_long,si7020_rh,si7020_tmp,sen0321_o3,sen0466_co,sen0470_so2,sen0471_no2,...,pm25_24h_emb_aqi,pm25_nowcast,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm10_who,o3_who
0,2023-08-01 01:00,9ef4b83d,14.6474,121.072,99.978085,26.991489,0.020447,0.0,0.0,421.276596,...,37.0,18.301277,64.0,37.0,19.606596,19.0,19.0,15,45,0.05
1,2023-08-01 02:00,9ef4b83d,14.6474,121.072,100.000000,26.985965,0.020000,0.0,0.0,421.052632,...,31.0,14.987160,57.0,30.0,17.177778,16.0,16.0,15,45,0.05
2,2023-08-01 03:00,9ef4b83d,14.6474,121.072,100.000000,27.002203,0.020000,0.0,0.0,415.254237,...,29.0,13.428256,54.0,27.0,15.962159,15.0,15.0,15,45,0.05
3,2023-08-01 04:00,9ef4b83d,14.6474,121.072,100.000000,27.001167,0.020000,0.0,0.0,421.666667,...,27.0,12.841172,52.0,26.0,15.595743,15.0,15.0,15,45,0.05
4,2023-08-01 05:00,9ef4b83d,14.6474,121.072,100.000000,27.016949,0.020000,0.0,0.0,415.254237,...,27.0,13.155492,53.0,26.0,15.708931,15.0,15.0,15,45,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5795,2024-03-29 12:00,9ef4b83d,14.6474,121.072,19.578167,26.508167,0.035050,0.0,0.0,468.333333,...,16.0,7.311497,30.0,15.0,13.397823,12.0,12.0,15,45,0.05
5796,2024-03-29 13:00,9ef4b83d,14.6474,121.072,17.895085,29.815085,0.049831,0.0,0.0,493.220339,...,16.0,7.044129,29.0,14.0,13.017644,12.0,12.0,15,45,0.05
5797,2024-03-29 14:00,9ef4b83d,14.6474,121.072,99.204333,33.690333,0.074100,0.0,0.0,516.666667,...,16.0,6.958472,29.0,14.0,12.870821,12.0,12.0,15,45,0.05
5798,2024-03-29 15:00,9ef4b83d,14.6474,121.072,89.525763,36.905932,0.071831,0.0,0.0,557.627119,...,16.0,6.511983,27.0,13.0,12.651798,12.0,12.0,15,45,0.05
5799,2024-03-29 16:00,9ef4b83d,14.6474,121.072,81.183000,38.096333,0.074750,0.0,0.0,545.000000,...,16.0,6.407456,27.0,13.0,12.296155,11.0,11.0,15,45,0.05

### Extract the date component from the datetime column

In [4]:
sensor_data['local_datetime'] = pd.to_datetime(sensor_data['local_time'])

### Exclude columns from resampling

In [5]:
# Columns to exclude from resampling
# Set datetime column as index
sensor_data.set_index('local_datetime', inplace=True, drop=False)
extra_columns = sensor_data[['gps_lat', 'gps_long']]
extra_columns

                     gps_lat  gps_long
local_datetime
2023-08-01 01:00:00  14.6474   121.072
2023-08-01 02:00:00  14.6474   121.072
2023-08-01 03:00:00  14.6474   121.072
2023-08-01 04:00:00  14.6474   121.072
2023-08-01 05:00:00  14.6474   121.072
...                      ...       ...
2024-03-29 12:00:00  14.6474   121.072
2024-03-29 13:00:00  14.6474   121.072
2024-03-29 14:00:00  14.6474   121.072
2024-03-29 15:00:00  14.6474   121.072
2024-03-29 16:00:00  14.6474   121.072

[5800 rows x 2 columns]

In [6]:
sensor_data

,local_time,source,gps_lat,gps_long,si7020_rh,si7020_tmp,sen0321_o3,sen0466_co,sen0470_so2,sen0471_no2,...,pm25_nowcast,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm10_who,o3_who,local_datetime
local_datetime,,,,,,,,,,,,,,,,,,,,,
2023-08-01 01:00:00,2023-08-01 01:00,9ef4b83d,14.6474,121.072,99.978085,26.991489,0.020447,0.0,0.0,421.276596,...,18.301277,64.0,37.0,19.606596,19.0,19.0,15,45,0.05,2023-08-01 01:00:00
2023-08-01 02:00:00,2023-08-01 02:00,9ef4b83d,14.6474,121.072,100.000000,26.985965,0.020000,0.0,0.0,421.052632,...,14.987160,57.0,30.0,17.177778,16.0,16.0,15,45,0.05,2023-08-01 02:00:00
2023-08-01 03:00:00,2023-08-01 03:00,9ef4b83d,14.6474,121.072,100.000000,27.002203,0.020000,0.0,0.0,415.254237,...,13.428256,54.0,27.0,15.962159,15.0,15.0,15,45,0.05,2023-08-01 03:00:00
2023-08-01 04:00:00,2023-08-01 04:00,9ef4b83d,14.6474,121.072,100.000000,27.001167,0.020000,0.0,0.0,421.666667,...,12.841172,52.0,26.0,15.595743,15.0,15.0,15,45,0.05,2023-08-01 04:00:00
2023-08-01 05:00:00,2023-08-01 05:00,9ef4b83d,14.6474,121.072,100.000000,27.016949,0.020000,0.0,0.0,415.254237,...,13.155492,53.0,26.0,15.708931,15.0,15.0,15,45,0.05,2023-08-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-29 12:00:00,2024-03-29 12:00,9ef4b83d,14.6474,121.072,19.578167,26.508167,0.035050,0.0,0.0,468.333333,...,7.311497,30.0,15.0,13.397823,12.0,12.0,15,45,0.05,2024-03-29 12:00:00
2024-03-29 13:00:00,2024-03-29 13:00,9ef4b83d,14.6474,121.072,17.895085,29.815085,0.049831,0.0,0.0,493.220339,...,7.044129,29.0,14.0,13.017644,12.0,12.0,15,45,0.05,2024-03-29 13:00:00
2024-03-29 14:00:00,2024-03-29 14:00,9ef4b83d,14.6474,121.072,99.204333,33.690333,0.074100,0.0,0.0,516.666667,...,6.958472,29.0,14.0,12.870821,12.0,12.0,15,45,0.05,2024-03-29 14:00:00
2024-03-29 15:00:00,2024-03-29 15:00,9ef4b83d,14.6474,121.072,89.525763,36.905932,0.071831,0.0,0.0,557.627119,...,6.511983,27.0,13.0,12.651798,12.0,12.0,15,45,0.05,2024-03-29 15:00:00
2024-03-29 16:00:00,2024-03-29 16:00,9ef4b83d,14.6474,121.072,81.183000,38.096333,0.074750,0.0,0.0,545.000000,...,6.407456,27.0,13.0,12.296155,11.0,11.0,15,45,0.05,2024-03-29 16:00:00

In [7]:
columns_to_exclude = ['gps_lat', 'gps_long']
sensor_data_dropped = sensor_data.drop(columns=columns_to_exclude)
sensor_data_dropped

,local_time,source,si7020_rh,si7020_tmp,sen0321_o3,sen0466_co,sen0470_so2,sen0471_no2,sps30_pm10_mass,sps30_pm2_0_mass,...,pm25_nowcast,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm10_who,o3_who,local_datetime
local_datetime,,,,,,,,,,,,,,,,,,,,,
2023-08-01 01:00:00,2023-08-01 01:00,9ef4b83d,99.978085,26.991489,0.020447,0.0,0.0,421.276596,19.606596,18.301277,...,18.301277,64.0,37.0,19.606596,19.0,19.0,15,45,0.05,2023-08-01 01:00:00
2023-08-01 02:00:00,2023-08-01 02:00,9ef4b83d,100.000000,26.985965,0.020000,0.0,0.0,421.052632,15.284386,12.689298,...,14.987160,57.0,30.0,17.177778,16.0,16.0,15,45,0.05,2023-08-01 02:00:00
2023-08-01 03:00:00,2023-08-01 03:00,9ef4b83d,100.000000,27.002203,0.020000,0.0,0.0,415.254237,14.475932,11.860508,...,13.428256,54.0,27.0,15.962159,15.0,15.0,15,45,0.05,2023-08-01 03:00:00
2023-08-01 04:00:00,2023-08-01 04:00,9ef4b83d,100.000000,27.001167,0.020000,0.0,0.0,421.666667,14.978000,12.054333,...,12.841172,52.0,26.0,15.595743,15.0,15.0,15,45,0.05,2023-08-01 04:00:00
2023-08-01 05:00:00,2023-08-01 05:00,9ef4b83d,100.000000,27.016949,0.020000,0.0,0.0,415.254237,15.933390,13.632203,...,13.155492,53.0,26.0,15.708931,15.0,15.0,15,45,0.05,2023-08-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-29 12:00:00,2024-03-29 12:00,9ef4b83d,19.578167,26.508167,0.035050,0.0,0.0,468.333333,12.833500,6.781833,...,7.311497,30.0,15.0,13.397823,12.0,12.0,15,45,0.05,2024-03-29 12:00:00
2024-03-29 13:00:00,2024-03-29 13:00,9ef4b83d,17.895085,29.815085,0.049831,0.0,0.0,493.220339,11.952542,6.700000,...,7.044129,29.0,14.0,13.017644,12.0,12.0,15,45,0.05,2024-03-29 13:00:00
2024-03-29 14:00:00,2024-03-29 14:00,9ef4b83d,99.204333,33.690333,0.074100,0.0,0.0,516.666667,12.439000,6.642333,...,6.958472,29.0,14.0,12.870821,12.0,12.0,15,45,0.05,2024-03-29 14:00:00
2024-03-29 15:00:00,2024-03-29 15:00,9ef4b83d,89.525763,36.905932,0.071831,0.0,0.0,557.627119,12.122542,6.024237,...,6.511983,27.0,13.0,12.651798,12.0,12.0,15,45,0.05,2024-03-29 15:00:00
2024-03-29 16:00:00,2024-03-29 16:00,9ef4b83d,81.183000,38.096333,0.074750,0.0,0.0,545.000000,11.385667,5.869500,...,6.407456,27.0,13.0,12.296155,11.0,11.0,15,45,0.05,2024-03-29 16:00:00

### Aggregate data using date and get its minimum, maximum, mean, and standard deviation

In [8]:
# Aggregate the data using date and get its min, max, mean, and standard deviation
sensor_data_min = sensor_data_dropped.resample('D', on='local_datetime').min()
sensor_data_max = sensor_data_dropped.resample('D', on='local_datetime').max()
sensor_data_mean = sensor_data_dropped.resample('D', on='local_datetime').mean()
sensor_data_std = sensor_data_dropped.resample('D', on='local_datetime').std()

In [9]:
print("sensor_data_min")
sensor_data_min

sensor_data_min

,local_time,source,si7020_rh,si7020_tmp,sen0321_o3,sen0466_co,sen0470_so2,sen0471_no2,sps30_pm10_mass,sps30_pm2_0_mass,...,pm25_nowcast,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm10_who,o3_who,local_datetime
local_datetime,,,,,,,,,,,,,,,,,,,,,
2023-08-01,2023-08-01 01:00,9ef4b83d,80.810333,24.746167,0.020000,0.0,0.0,403.448276,14.258475,11.599322,...,12.831540,52.0,26.0,15.293848,14.0,14.0,15,45,0.05,2023-08-01 01:00:00
2023-08-02,2023-08-02 00:00,9ef4b83d,83.119667,24.956441,0.020000,0.0,0.0,401.694915,12.231525,6.718644,...,13.677070,54.0,27.0,18.313237,17.0,17.0,15,45,0.05,2023-08-02 00:00:00
2023-08-03,2023-08-03 00:00,9ef4b83d,80.348305,26.155932,0.020000,0.0,0.0,408.333333,10.642586,5.535690,...,6.384398,27.0,13.0,11.278503,10.0,10.0,15,45,0.05,2023-08-03 00:00:00
2023-08-04,2023-08-04 00:00,9ef4b83d,80.103390,23.708000,0.020000,0.0,0.0,406.666667,10.890339,6.110000,...,6.592183,28.0,13.0,11.951430,11.0,11.0,15,45,0.05,2023-08-04 00:00:00
2023-08-05,2023-08-05 00:00,9ef4b83d,NaN,NaN,0.028633,0.0,0.0,435.000000,311.633833,346.207833,...,303.359296,353.0,464.0,290.349466,168.0,168.0,15,45,0.05,2023-08-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-25,2024-03-25 00:00,9ef4b83d,57.796000,26.384746,0.027467,0.0,0.0,485.714286,11.422500,7.375500,...,7.865392,33.0,16.0,12.809966,12.0,12.0,15,45,0.05,2024-03-25 00:00:00
2024-03-26,2024-03-26 00:00,9ef4b83d,69.695763,27.514915,0.025033,0.0,0.0,500.000000,11.536000,6.023500,...,7.012376,29.0,14.0,12.539967,12.0,12.0,15,45,0.05,2024-03-26 00:00:00
2024-03-27,2024-03-27 00:00,9ef4b83d,4.757018,26.061186,0.023356,0.0,0.0,475.000000,11.440339,5.708814,...,6.805097,28.0,14.0,13.063959,12.0,12.0,15,45,0.05,2024-03-27 00:00:00
2024-03-28,2024-03-28 00:00,9ef4b83d,3.756897,26.218983,0.023847,0.0,0.0,486.206897,10.722833,5.110667,...,5.603029,23.0,11.0,11.515603,11.0,11.0,15,45,0.05,2024-03-28 00:00:00
2024-03-29,2024-03-29 00:00,9ef4b83d,0.959661,26.508167,0.021915,0.0,0.0,468.333333,11.385667,5.869500,...,6.407456,27.0,13.0,12.296155,11.0,11.0,15,45,0.05,2024-03-29 00:00:00

In [10]:
# Drop the following columns as they exist already in sensor_data_min
sensor_data_max = sensor_data_max.drop(columns=["local_time", "source", "local_datetime"])
print("sensor_data_max")
sensor_data_max

sensor_data_max

,si7020_rh,si7020_tmp,sen0321_o3,sen0466_co,sen0470_so2,sen0471_no2,sps30_pm10_mass,sps30_pm2_0_mass,o3_8h,o3_1h,...,pm25_24h_emb_aqi,pm25_nowcast,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm10_who,o3_who
local_datetime,,,,,,,,,,,,,,,,,,,,,
2023-08-01,100.000000,27.109831,0.025267,0.0,0.0,425.000000,39.006333,38.124833,0.021646,0.025267,...,37.0,32.219867,93.0,86.0,33.143816,31.0,31.0,15,45,0.05
2023-08-02,100.000000,28.012712,0.027033,0.0,0.0,431.666667,371.974746,373.778475,0.023746,0.027033,...,393.0,327.641930,377.0,483.0,352.788749,200.0,200.0,15,45,0.05
2023-08-03,99.374333,28.327667,0.038576,0.0,0.0,428.813559,48.630000,39.494333,0.031558,0.038576,...,383.0,28.740778,86.0,69.0,34.502198,32.0,32.0,15,45,0.05
2023-08-04,99.534333,28.492167,0.036036,0.0,0.0,430.909091,365.466610,335.946102,0.029499,0.036036,...,142.0,260.428057,311.0,431.0,268.992288,158.0,158.0,15,45,0.05
2023-08-05,NaN,NaN,0.028633,0.0,0.0,435.000000,311.633833,346.207833,0.029742,0.028633,...,497.0,346.207833,396.0,497.0,327.317844,187.0,187.0,15,45,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-25,100.000000,39.178136,0.093850,0.0,0.0,652.542373,24.650500,18.004500,0.075696,0.093850,...,22.0,14.811564,57.0,30.0,20.688715,19.0,19.0,15,45,0.05
2024-03-26,100.000000,40.123559,0.082492,0.0,0.0,668.333333,25.903667,21.211667,0.070471,0.082492,...,26.0,18.308846,64.0,37.0,23.588612,22.0,22.0,15,45,0.05
2024-03-27,100.000000,38.452581,0.075729,0.0,0.0,659.322034,18.234746,12.414237,0.065219,0.075729,...,22.0,11.268167,47.0,23.0,16.836849,16.0,16.0,15,45,0.05
2024-03-28,100.000000,41.010169,0.099583,0.0,0.0,641.666667,16.665333,11.208475,0.078308,0.099583,...,18.0,9.549305,40.0,19.0,14.670159,14.0,14.0,15,45,0.05
2024-03-29,100.000000,38.096333,0.097683,0.0,0.0,573.333333,15.904667,10.527833,0.069116,0.097683,...,16.0,9.286515,39.0,19.0,14.380273,13.0,13.0,15,45,0.05

In [11]:
print("sensor_data_mean")
sensor_data_mean

sensor_data_mean

,si7020_rh,si7020_tmp,sen0321_o3,sen0466_co,sen0470_so2,sen0471_no2,sps30_pm10_mass,sps30_pm2_0_mass,o3_8h,o3_1h,...,pm25_24h_emb_aqi,pm25_nowcast,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm10_who,o3_who
local_datetime,,,,,,,,,,,,,,,,,,,,,
2023-08-01,95.245280,26.101804,0.020786,0.0,0.0,413.829364,19.197439,17.321107,0.020752,0.020786,...,29.086957,16.516889,60.260870,34.217391,18.388769,17.304348,17.304348,15.0,45.0,0.05
2023-08-02,94.140518,26.486036,0.021477,0.0,0.0,415.056497,207.479741,207.564726,0.021500,0.021477,...,328.958333,207.757127,261.250000,339.791667,208.887014,124.791667,124.791667,15.0,45.0,0.05
2023-08-03,92.245075,27.404289,0.024293,0.0,0.0,419.476833,14.552421,9.499549,0.024287,0.024293,...,172.666667,9.704756,37.750000,20.000000,14.682456,13.500000,13.500000,15.0,45.0,0.05
2023-08-04,88.915853,26.539942,0.025996,0.0,0.0,420.952427,49.832516,43.402713,0.024718,0.025996,...,27.333333,32.909104,67.833333,71.166667,39.256763,29.041667,29.041667,15.0,45.0,0.05
2023-08-05,NaN,NaN,0.028633,0.0,0.0,435.000000,311.633833,346.207833,0.028773,0.028633,...,324.833333,314.606570,364.583333,472.583333,299.681201,173.000000,173.000000,15.0,45.0,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-25,84.325193,32.049286,0.052811,0.0,0.0,556.221073,16.401201,10.810596,0.052310,0.052811,...,19.500000,10.508204,43.166667,21.083333,16.096478,15.125000,15.125000,15.0,45.0,0.05
2024-03-26,89.028245,32.955473,0.046542,0.0,0.0,561.667242,16.876386,11.520522,0.047349,0.046542,...,24.708333,11.735653,45.291667,23.500000,17.044120,15.625000,15.625000,15.0,45.0,0.05
2024-03-27,61.752368,30.678192,0.042592,0.0,0.0,539.240171,14.515015,9.179036,0.044161,0.042592,...,18.708333,9.269121,38.500000,18.500000,14.644588,13.708333,13.708333,15.0,45.0,0.05
2024-03-28,65.284080,32.998663,0.051852,0.0,0.0,546.252871,13.015242,7.333340,0.050072,0.051852,...,15.750000,7.256312,30.250000,14.416667,12.902680,11.958333,11.958333,15.0,45.0,0.05
2024-03-29,65.768152,31.834866,0.051949,0.0,0.0,517.688601,13.267425,7.442182,0.046250,0.051949,...,15.470588,7.637442,31.764706,15.294118,13.543210,12.588235,12.588235,15.0,45.0,0.05

In [12]:
print("sensor_data_std")
sensor_data_std

sensor_data_std

,si7020_rh,si7020_tmp,sen0321_o3,sen0466_co,sen0470_so2,sen0471_no2,sps30_pm10_mass,sps30_pm2_0_mass,o3_8h,o3_1h,...,pm25_24h_emb_aqi,pm25_nowcast,pm25_nowcast_aqi,pm25_nowcast_emb_aqi,pm10_nowcast,pm10_nowcast_aqi,pm10_nowcast_emb_aqi,pm25_who,pm10_who,o3_who
local_datetime,,,,,,,,,,,,,,,,,,,,,
2023-08-01,6.367252,0.856405,0.001283,0.0,0.0,6.406175,5.964556,6.527553,0.000586,0.001283,...,2.778375,5.023810,10.613959,13.839852,4.422543,3.993572,3.993572,0.0,0.0,0.0
2023-08-02,5.596890,0.985871,0.002050,0.0,0.0,8.520326,150.127785,151.513918,0.001179,0.002050,...,91.547317,131.987505,128.684397,180.336637,134.017557,71.408183,71.408183,0.0,0.0,0.0
2023-08-03,6.294733,0.862768,0.006247,0.0,0.0,6.203076,7.980871,7.634542,0.004108,0.006247,...,150.249261,5.333139,14.961545,12.507389,5.241807,4.978213,4.978213,0.0,0.0,0.0
2023-08-04,7.765380,1.725780,0.005646,0.0,0.0,5.829750,93.108855,90.592287,0.003969,0.005646,...,27.404644,64.285217,76.308109,121.134014,66.541165,39.054565,39.054565,0.0,0.0,0.0
2023-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000949,NaN,...,88.567668,14.775688,14.786101,11.429295,12.055901,6.000000,6.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-25,15.576126,4.559872,0.019993,0.0,0.0,59.463574,2.992544,2.861311,0.014997,0.019993,...,0.834058,2.256632,8.239178,4.500403,2.242041,2.251811,2.251811,0.0,0.0,0.0
2024-03-26,11.684431,4.060135,0.018946,0.0,0.0,56.283037,4.494721,4.776311,0.013407,0.018946,...,1.232853,4.320167,13.530896,8.682817,4.037028,3.597251,3.597251,0.0,0.0,0.0
2024-03-27,36.504823,4.356071,0.017156,0.0,0.0,59.147071,1.955328,1.942153,0.010211,0.017156,...,1.398109,1.074577,4.549247,2.186918,0.996386,1.041703,1.041703,0.0,0.0,0.0
2024-03-28,38.111816,5.225333,0.023988,0.0,0.0,52.682458,1.745455,1.770766,0.019625,0.023988,...,1.326978,1.358093,5.712306,2.764946,0.996734,0.954585,0.954585,0.0,0.0,0.0
2024-03-29,37.654725,3.713291,0.024242,0.0,0.0,31.281842,1.442953,1.353040,0.013896,0.024242,...,0.514496,0.770681,3.250566,1.611083,0.575179,0.618347,0.618347,0.0,0.0,0.0

### Combine these data into one array

In [13]:
# Rename columns with "_min", "_max", "_std" suffixes
columns_to_retain = ['local_time', 'source', 'local_datetime']

sensor_data_min.columns = [f"{col}_min" if col not in columns_to_retain else col for col in sensor_data_min.columns]
sensor_data_max.columns = [f"{col}_max" if col not in columns_to_retain else col for col in sensor_data_max.columns]
sensor_data_mean.columns = [f"{col}_std" if col not in columns_to_retain else col for col in sensor_data_mean.columns]
sensor_data_std.columns = [f"{col}_std" if col not in columns_to_retain else col for col in sensor_data_std.columns]

In [14]:
# Combine DataFrames into one
daily_data_combined = pd.concat([sensor_data_min, sensor_data_max, sensor_data_mean, sensor_data_std], axis=1)

# Print the combined DataFrame
print(daily_data_combined)

                      local_time    source  si7020_rh_min  si7020_tmp_min  \
local_datetime
2023-08-01      2023-08-01 01:00  9ef4b83d      80.810333       24.746167
2023-08-02      2023-08-02 00:00  9ef4b83d      83.119667       24.956441
2023-08-03      2023-08-03 00:00  9ef4b83d      80.348305       26.155932
2023-08-04      2023-08-04 00:00  9ef4b83d      80.103390       23.708000
2023-08-05      2023-08-05 00:00  9ef4b83d            NaN             NaN
...                          ...       ...            ...             ...
2024-03-25      2024-03-25 00:00  9ef4b83d      57.796000       26.384746
2024-03-26      2024-03-26 00:00  9ef4b83d      69.695763       27.514915
2024-03-27      2024-03-27 00:00  9ef4b83d       4.757018       26.061186
2024-03-28      2024-03-28 00:00  9ef4b83d       3.756897       26.218983
2024-03-29      2024-03-29 00:00  9ef4b83d       0.959661       26.508167

                sen0321_o3_min  sen0466_co_min  sen0470_so2_min  \
local_datetime
2023-08-01            0.020000             0.0              0.0
2023-08-02            0.020000             0.0              0.0
2023-08-03            0.020000             0.0              0.0
2023-08-04            0.020000             0.0              0.0
2023-08-05            0.028633             0.0              0.0
...                        ...             ...              ...
2024-03-25            0.027467             0.0              0.0
2024-03-26            0.025033             0.0              0.0
2024-03-27            0.023356             0.0              0.0
2024-03-28            0.023847             0.0              0.0
2024-03-29            0.021915             0.0              0.0

                sen0471_no2_min  sps30_pm10_mass_min  sps30_pm2_0_mass_min  \
local_datetime
2023-08-01           403.448276            14.258475             11.599322
2023-08-02           401.694915            12.231525              6.718644
2023-08-03           408.333333            10.642586              5.535690
2023-08-04           406.666667            10.890339              6.110000
2023-08-05           435.000000           311.633833            346.207833
...                         ...                  ...                   ...
2024-03-25           485.714286            11.422500              7.375500
2024-03-26           500.000000            11.536000              6.023500
2024-03-27           475.000000            11.440339              5.708814
2024-03-28           486.206897            10.722833              5.110667
2024-03-29           468.333333            11.385667              5.869500

                ...  pm25_24h_emb_aqi_std  pm25_nowcast_std  \
local_datetime  ...
2023-08-01      ...              2.778375          5.023810
2023-08-02      ...             91.547317        131.987505
2023-08-03      ...            150.249261          5.333139
2023-08-04      ...             27.404644         64.285217
2023-08-05      ...             88.567668         14.775688
...             ...                   ...               ...
2024-03-25      ...              0.834058          2.256632
2024-03-26      ...              1.232853          4.320167
2024-03-27      ...              1.398109          1.074577
2024-03-28      ...              1.326978          1.358093
2024-03-29      ...              0.514496          0.770681

                pm25_nowcast_aqi_std  pm25_nowcast_emb_aqi_std  \
local_datetime
2023-08-01                 10.613959                 13.839852
2023-08-02                128.684397                180.336637
2023-08-03                 14.961545                 12.507389
2023-08-04                 76.308109                121.134014
2023-08-05                 14.786101                 11.429295
...                              ...                       ...
2024-03-25                  8.239178                  4.500403
2024-03-26                 13.530896                  8.682817
2024-03-27                  4.549247                  2.186918
2024-03-28                  5.712306                  2.764946
2024-03-29                  3.250566                  1.611083

                pm10_nowcast_std  pm10_nowcast_aqi_std  \
local_datetime
2023-08-01              4.422543              3.993572
2023-08-02            134.017557             71.408183
2023-08-03              5.241807              4.978213
2023-08-04             66.541165             39.054565
2023-08-05             12.055901              6.000000
...                          ...                   ...
2024-03-25              2.242041              2.251811
2024-03-26              4.037028              3.597251
2024-03-27              0.996386              1.041703
2024-03-28              0.996734              0.954585
2024-03-29              0.575179              0.618347

                pm10_nowcast_emb_aqi_std  pm25_who_std  pm10_who_std  \
local_datetime
2023-08-01                      3.993572           0.0           0.0
2023-08-02                     71.408183           0.0           0.0
2023-08-03                      4.978213           0.0           0.0
2023-08-04                     39.054565           0.0           0.0
2023-08-05                      6.000000           0.0           0.0
...                                  ...           ...           ...
2024-03-25                      2.251811           0.0           0.0
2024-03-26                      3.597251           0.0           0.0
2024-03-27                      1.041703           0.0           0.0
2024-03-28                      0.954585           0.0           0.0
2024-03-29                      0.618347           0.0           0.0

                o3_who_std
local_datetime
2023-08-01             0.0
2023-08-02             0.0
2023-08-03             0.0
2023-08-04             0.0
2023-08-05             0.0
...                    ...
2024-03-25             0.0
2024-03-26             0.0
2024-03-27             0.0
2024-03-28             0.0
2024-03-29             0.0

[242 rows x 155 columns]

In [15]:
# Concatenate extra columns back to the result
daily_data_combined = pd.concat([daily_data_combined, extra_columns.reindex(daily_data_combined.index)], axis=1)
daily_data_combined

,local_time,source,si7020_rh_min,si7020_tmp_min,sen0321_o3_min,sen0466_co_min,sen0470_so2_min,sen0471_no2_min,sps30_pm10_mass_min,sps30_pm2_0_mass_min,...,pm25_nowcast_aqi_std,pm25_nowcast_emb_aqi_std,pm10_nowcast_std,pm10_nowcast_aqi_std,pm10_nowcast_emb_aqi_std,pm25_who_std,pm10_who_std,o3_who_std,gps_lat,gps_long
local_datetime,,,,,,,,,,,,,,,,,,,,,
2023-08-01,2023-08-01 01:00,9ef4b83d,80.810333,24.746167,0.020000,0.0,0.0,403.448276,14.258475,11.599322,...,10.613959,13.839852,4.422543,3.993572,3.993572,0.0,0.0,0.0,NaN,NaN
2023-08-02,2023-08-02 00:00,9ef4b83d,83.119667,24.956441,0.020000,0.0,0.0,401.694915,12.231525,6.718644,...,128.684397,180.336637,134.017557,71.408183,71.408183,0.0,0.0,0.0,14.6474,121.072
2023-08-03,2023-08-03 00:00,9ef4b83d,80.348305,26.155932,0.020000,0.0,0.0,408.333333,10.642586,5.535690,...,14.961545,12.507389,5.241807,4.978213,4.978213,0.0,0.0,0.0,14.6474,121.072
2023-08-04,2023-08-04 00:00,9ef4b83d,80.103390,23.708000,0.020000,0.0,0.0,406.666667,10.890339,6.110000,...,76.308109,121.134014,66.541165,39.054565,39.054565,0.0,0.0,0.0,14.6474,121.072
2023-08-05,2023-08-05 00:00,9ef4b83d,NaN,NaN,0.028633,0.0,0.0,435.000000,311.633833,346.207833,...,14.786101,11.429295,12.055901,6.000000,6.000000,0.0,0.0,0.0,14.6474,121.072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-25,2024-03-25 00:00,9ef4b83d,57.796000,26.384746,0.027467,0.0,0.0,485.714286,11.422500,7.375500,...,8.239178,4.500403,2.242041,2.251811,2.251811,0.0,0.0,0.0,14.6474,121.072
2024-03-26,2024-03-26 00:00,9ef4b83d,69.695763,27.514915,0.025033,0.0,0.0,500.000000,11.536000,6.023500,...,13.530896,8.682817,4.037028,3.597251,3.597251,0.0,0.0,0.0,14.6474,121.072
2024-03-27,2024-03-27 00:00,9ef4b83d,4.757018,26.061186,0.023356,0.0,0.0,475.000000,11.440339,5.708814,...,4.549247,2.186918,0.996386,1.041703,1.041703,0.0,0.0,0.0,14.6474,121.072
2024-03-28,2024-03-28 00:00,9ef4b83d,3.756897,26.218983,0.023847,0.0,0.0,486.206897,10.722833,5.110667,...,5.712306,2.764946,0.996734,0.954585,0.954585,0.0,0.0,0.0,14.6474,121.072
2024-03-29,2024-03-29 00:00,9ef4b83d,0.959661,26.508167,0.021915,0.0,0.0,468.333333,11.385667,5.869500,...,3.250566,1.611083,0.575179,0.618347,0.618347,0.0,0.0,0.0,14.6474,121.072

In [16]:
daily_data_combined.to_csv(f'sensor_data/output/sensor_daily_data.csv')